/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'featured-projects': FeaturedProject;
    'portfolio-items': PortfolioItem;
    'pain-points': PainPoint;
    'client-logos': ClientLogo;
    'homepage-case-studies': HomepageCaseStudy;
    testimonials: Testimonial;
    'faq-items': FaqItem;
    clients: Client;
    'case-studies': CaseStudy;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'featured-projects': FeaturedProjectsSelect<false> | FeaturedProjectsSelect<true>;
    'portfolio-items': PortfolioItemsSelect<false> | PortfolioItemsSelect<true>;
    'pain-points': PainPointsSelect<false> | PainPointsSelect<true>;
    'client-logos': ClientLogosSelect<false> | ClientLogosSelect<true>;
    'homepage-case-studies': HomepageCaseStudiesSelect<false> | HomepageCaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-footer': SiteFooter;
  };
  globalsSelect: {
    'site-footer': SiteFooterSelect<false> | SiteFooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * Original public path used by seed, for idempotent upserts.
   */
  sourcePath?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  tags: {
    label: string;
    id?: string | null;
  }[];
  icon: 'stack' | 'grid';
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-projects".
 */
export interface FeaturedProject {
  id: number;
  name: string;
  description: string;
  metric: string;
  metricLabel: string;
  image: number | Media;
  alt: string;
  /**
   * Card opens this Client: Hub → /clients/{slug}; Direct → that client’s featured case study.
   */
  client: number | Client;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * One record per brand. Hub = 2+ projects (library). Direct = one project, skip hub.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  /**
   * URL: /clients/{slug}. Example: sevenloop, puma.
   */
  slug: string;
  /**
   * Homepage cards follow this. Hub = library. Direct = one study. If creating from a Case study, save the Client first — Featured study fills in after the study is saved.
   */
  projectType: 'hub' | 'direct';
  /**
   * Homepage opens this study when Project type is Direct. Create the Case study first (or save this Client, then the study) — do not create a study from this field.
   */
  featuredStudy?: (number | null) | CaseStudy;
  navItems?:
    | {
        navId: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  about?: {
    italic: string;
    rest: string;
    body: string;
    websiteHref: string;
  };
  logoDesign?: {
    italic: string;
    rest: string;
    images?:
      | {
          image: number | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional — open this case study from Logo Design.
     */
    caseStudy?: (number | null) | CaseStudy;
  };
  websiteDesign?: {
    italic: string;
    rest: string;
    image: {
      image: number | Media;
      alt: string;
      id?: string | null;
    };
    /**
     * Optional — open this case study from Website Design.
     */
    caseStudy?: (number | null) | CaseStudy;
  };
  projectBrochure?: {
    italic: string;
    rest: string;
    images?:
      | {
          image: number | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional — open this case study from Project Brochure.
     */
    caseStudy?: (number | null) | CaseStudy;
  };
  brandVideo?: {
    italic: string;
    rest: string;
    /**
     * Still poster only (JPG/PNG). Upload the MP4 in Video.
     */
    image: {
      image: number | Media;
      alt: string;
      id?: string | null;
    };
    /**
     * MP4 or WebM for playback. Put a still JPG/PNG in Image — not the video file.
     */
    video?: (number | null) | Media;
    /**
     * Optional — open this case study from Brand Video.
     */
    caseStudy?: (number | null) | CaseStudy;
  };
  behindTheScenes?: {
    italic: string;
    rest: string;
    images?:
      | {
          image: number | Media;
          alt: string;
          id?: string | null;
        }[]
      | null;
  };
  caseStudy?: {
    italic: string;
    rest: string;
    subheading: string;
    /**
     * Primary Case Study CTA on the hub.
     */
    caseStudy?: (number | null) | CaseStudy;
  };
  partnership?: {
    label: string;
    heading: string;
    headingAccent: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  transformation?: {
    heading: string;
    subtext: string;
    before: {
      image: number | Media;
      alt: string;
      id?: string | null;
    };
    after: {
      image: number | Media;
      alt: string;
      id?: string | null;
    };
  };
  projectTeam?: {
    heading: string;
    subheading: string;
    members?:
      | {
          name: string;
          role: string;
          photo: {
            image: number | Media;
            alt: string;
            id?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Belongs to a Client. Hub clients can have many; a Direct client usually has one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * URL: /clients/{client}/{slug}. Example: case-study, website, branding.
   */
  slug: string;
  /**
   * The brand this study belongs to. If the Client does not exist yet, create and save it first — leave Featured study empty. After you save this Case study, Direct clients pick it up automatically.
   */
  client: number | Client;
  hero: {
    heading: string;
    /**
     * Last breadcrumb crumb. Defaults to the study title.
     */
    breadcrumbCurrent?: string | null;
    /**
     * Optional. Leave empty to auto-build Home / clients / {client}.
     */
    breadcrumb?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    image: {
      image: number | Media;
      alt: string;
      id?: string | null;
    };
  };
  details: {
    quote: string;
    /**
     * Heading shown above the table — e.g. "Details". This is a caption on its own, not a row, so it has no value beside it. Add label/value pairs under Rows below.
     */
    tableHeading: string;
    /**
     * Each row is a label/value pair (e.g. Client → Sevenloop). If you leave this empty the page falls back to placeholder rows.
     */
    rows?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  gallery?:
    | {
        image: number | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  viewAll: {
    label: string;
    href: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-items".
 */
export interface PortfolioItem {
  id: number;
  name: string;
  category: string;
  image: number | Media;
  alt: string;
  /**
   * Card opens this Client: Hub → /clients/{slug}; Direct → that client’s featured case study.
   */
  client: number | Client;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pain-points".
 */
export interface PainPoint {
  id: number;
  tag: string;
  quote: string;
  resolution: string;
  /**
   * Card opens this Client: Hub → /clients/{slug}; Direct → that client’s featured case study.
   */
  client: number | Client;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos".
 */
export interface ClientLogo {
  id: number;
  name: string;
  image: number | Media;
  width: number;
  height: number;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-case-studies".
 */
export interface HomepageCaseStudy {
  id: number;
  number: string;
  name: string;
  description: string;
  tags: {
    label: string;
    id?: string | null;
  }[];
  /**
   * Row opens this case study — /clients/{client}/{study}. Pick the project itself, not the brand.
   */
  caseStudy: number | CaseStudy;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Still poster (JPG/PNG/WebP). Do not put the MP4 here — use Video below.
   */
  image?: (number | null) | Media;
  /**
   * MP4 or WebM for playback. Put a still JPG/PNG in Image — not the video file.
   */
  video?: (number | null) | Media;
  alt: string;
  quote?: string | null;
  /**
   * On-screen card width. Prefills to the homepage size (290).
   */
  width: number;
  /**
   * On-screen card height. Prefills to 320; the center card is taller on desktop via layout.
   */
  height: number;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer?: string | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'featured-projects';
        value: number | FeaturedProject;
      } | null)
    | ({
        relationTo: 'portfolio-items';
        value: number | PortfolioItem;
      } | null)
    | ({
        relationTo: 'pain-points';
        value: number | PainPoint;
      } | null)
    | ({
        relationTo: 'client-logos';
        value: number | ClientLogo;
      } | null)
    | ({
        relationTo: 'homepage-case-studies';
        value: number | HomepageCaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourcePath?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-projects_select".
 */
export interface FeaturedProjectsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  metric?: T;
  metricLabel?: T;
  image?: T;
  alt?: T;
  client?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-items_select".
 */
export interface PortfolioItemsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  image?: T;
  alt?: T;
  client?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pain-points_select".
 */
export interface PainPointsSelect<T extends boolean = true> {
  tag?: T;
  quote?: T;
  resolution?: T;
  client?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos_select".
 */
export interface ClientLogosSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  width?: T;
  height?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-case-studies_select".
 */
export interface HomepageCaseStudiesSelect<T extends boolean = true> {
  number?: T;
  name?: T;
  description?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  caseStudy?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  image?: T;
  video?: T;
  alt?: T;
  quote?: T;
  width?: T;
  height?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  projectType?: T;
  featuredStudy?: T;
  navItems?:
    | T
    | {
        navId?: T;
        label?: T;
        id?: T;
      };
  about?:
    | T
    | {
        italic?: T;
        rest?: T;
        body?: T;
        websiteHref?: T;
      };
  logoDesign?:
    | T
    | {
        italic?: T;
        rest?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        caseStudy?: T;
      };
  websiteDesign?:
    | T
    | {
        italic?: T;
        rest?: T;
        image?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        caseStudy?: T;
      };
  projectBrochure?:
    | T
    | {
        italic?: T;
        rest?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        caseStudy?: T;
      };
  brandVideo?:
    | T
    | {
        italic?: T;
        rest?: T;
        image?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        video?: T;
        caseStudy?: T;
      };
  behindTheScenes?:
    | T
    | {
        italic?: T;
        rest?: T;
        images?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  caseStudy?:
    | T
    | {
        italic?: T;
        rest?: T;
        subheading?: T;
        caseStudy?: T;
      };
  partnership?:
    | T
    | {
        label?: T;
        heading?: T;
        headingAccent?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  transformation?:
    | T
    | {
        heading?: T;
        subtext?: T;
        before?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
        after?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  projectTeam?:
    | T
    | {
        heading?: T;
        subheading?: T;
        members?:
          | T
          | {
              name?: T;
              role?: T;
              photo?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  hero?:
    | T
    | {
        heading?: T;
        breadcrumbCurrent?: T;
        breadcrumb?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        image?:
          | T
          | {
              image?: T;
              alt?: T;
              id?: T;
            };
      };
  details?:
    | T
    | {
        quote?: T;
        tableHeading?: T;
        rows?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  viewAll?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer".
 */
export interface SiteFooter {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  aiLinks?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer_select".
 */
export interface SiteFooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  aiLinks?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}